In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set_style('whitegrid')

In [2]:
dataset = pd.read_csv('admitance.csv')

In [3]:
dataset

SAT Admitted
0    1363       No
1    1792      Yes
2    1954      Yes
3    1653       No
4    1593       No
..    ...      ...
163  1722      Yes
164  1750      Yes
165  1555       No
166  1524       No
167  1461       No

[168 rows x 2 columns]

In [4]:
dataset['Admitted'] = dataset['Admitted'].map({'Yes' : 1,'No':0})

In [5]:
dataset

SAT  Admitted
0    1363         0
1    1792         1
2    1954         1
3    1653         0
4    1593         0
..    ...       ...
163  1722         1
164  1750         1
165  1555         0
166  1524         0
167  1461         0

[168 rows x 2 columns]

In [6]:
X = dataset['SAT']

In [7]:
X

0      1363
1      1792
2      1954
3      1653
4      1593
       ... 
163    1722
164    1750
165    1555
166    1524
167    1461
Name: SAT, Length: 168, dtype: int64

In [8]:
y = dataset['Admitted']

In [9]:
y

0      0
1      1
2      1
3      0
4      0
      ..
163    1
164    1
165    0
166    0
167    0
Name: Admitted, Length: 168, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
X_train

61     1715
44     1810
24     1720
63     1842
89     1687
       ... 
9      1580
103    1579
67     1521
117    1475
47     1477
Name: SAT, Length: 134, dtype: int64

In [13]:
X_test.shape

(34,)

In [22]:
X_test= np.array([X_test])

In [39]:
X_test

array([[[1933, 1670, 1430, 1550, 1775, 2050, 1887, 1755, 1473, 1502,
         1934, 1494, 1850, 1531, 1794, 1414, 1855, 1550, 1557, 1843,
         1824, 1769, 1956, 1524, 1385, 1832, 1634, 1773, 1487, 2020,
         1893, 1481, 1508, 1872]]], dtype=int64)

In [46]:
x = X_test.reshape(34,1)

In [47]:
x

array([[1933],
       [1670],
       [1430],
       [1550],
       [1775],
       [2050],
       [1887],
       [1755],
       [1473],
       [1502],
       [1934],
       [1494],
       [1850],
       [1531],
       [1794],
       [1414],
       [1855],
       [1550],
       [1557],
       [1843],
       [1824],
       [1769],
       [1956],
       [1524],
       [1385],
       [1832],
       [1634],
       [1773],
       [1487],
       [2020],
       [1893],
       [1481],
       [1508],
       [1872]], dtype=int64)

In [48]:
x.shape

(34, 1)

In [49]:
from sklearn.linear_model import LogisticRegression

In [50]:
model = LogisticRegression()

In [54]:
model.fit(x,y_test)

LogisticRegression()

In [55]:
y_test

151    1
56     0
123    0
60     0
100    1
51     1
7      1
5      1
86     0
135    0
54     1
94     0
157    1
101    0
73     1
45     0
74     1
97     0
139    0
96     1
107    1
106    1
150    1
166    0
55     0
152    1
26     1
143    1
155    0
33     1
8      1
108    0
122    0
37     1
Name: Admitted, dtype: int64

In [57]:
y_pred = model.predict(x)

In [58]:
y_pred

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [59]:
from sklearn.metrics import confusion_matrix

In [62]:
print(confusion_matrix(y_test,y_pred))

[[14  1]
 [ 1 18]]
